### ISSUE TITLE
Install mongoclient and connect to the docker instance of mongo

### ISSUE THREAD

**Issue by neilwilliams** [neilwilliams/painting#12]
After you run:
> docker-compose up  

The docker mongo instance should be running on localhost port 27017.

Familiarise yourself with this client. I haven't used it much myself, but one of the guys uses it in work.

https://github.com/rsercano/mongoclient/releases/tag/1.4.0

**Comment by neilwilliams** [comment]
I think you've done this now @craigdavies7? I'll close.

**Comment by craigdavies7** [comment]
Yes, had mongo client up and running with docker mongo db instance.
