### ISSUE TITLE
Investigate different mongo modules for the play framework

### ISSUE THREAD

**Issue by neilwilliams** [neilwilliams/painting#13]
- http://reactivemongo.org/
  - https://github.com/ReactiveMongo/Play-ReactiveMongo
- http://jongo.org/
  - https://github.com/alexanderjarvis/play-jongo

More?

**Comment by craigdavies7** [comment]
https://github.com/knoldus/playing-reactive-mongo

check this out.

**Comment by neilwilliams** [comment]
We're running with Jongo for now. Once we have more experience of Java then maybe we can go with reactive mongo if we stick with this.
