### ISSUE TITLE
Investigate into using Spring MVC instead of Play

### ISSUE THREAD

**Issue by neilwilliams** [neilwilliams/painting#18]
I'm adding an issue here, as I'm still considering this our main project.

After a good night on Play, I'm discovering it's very easy to work with once you get to know things.
Plus I've improved the docker build loads too now, so it's quicker to rebuild and we have proper debugging with intelli j. :)

It makes sense to look into other frameworks too, but in my opinion, we need more reasons to jump ship other than this framework is newer, and there's not many sample applications written. We've decided to go with Java over scala, which less people seem to do. But the play docs are very good, for java too.

https://playframework.com/documentation/2.5.x/JavaHome

**Comment by craigdavies7** [comment]
I'm going to abondon the Spring idea as you've made some really good ground with Play and I'd rather concentrate efforts on sticking with this one framework now. I'm going to close this issue.
